# Generated by Django 4.2.2 on 2023-06-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.CharField(max_length=150)),
                ('professor', models.CharField(choices=[('1', 'Orlando'), ('2', 'Mendes')], max_length=150)),
            ],
        ),
    ]
