# Generated by Django 4.2.2 on 2023-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=150, verbose_name='nomeCompleto')),
                ('professores', models.CharField(max_length=150, verbose_name='professores')),
            ],
        ),
    ]
